version: 2.1

orbs:
  ci: matic/orb-common@0.3
  ruby: circleci/ruby@2.5.3

jobs:

  rspec-test:
    resource_class: small
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - run:
          name: Checkout code via HTTPS
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/matic-insurance/matic-jwt-wrapper.git .
            git checkout ${CIRCLE_SHA1}
      - ruby/install-deps
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec
      - store_test_results:
          path: reports/rspec
      - store_artifacts:
          path: reports/rspec
      - ci/slack-stage-message

  release:
    parameters:
      tag:
        type: string
        default: "default-tag"
    docker:
      - image: cimg/ruby:3.1.4
    environment:
      RELEASE_TAG: << parameters.tag >>
    steps:
      - run:
          name: Checkout code via HTTPS
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/matic-insurance/matic-jwt-wrapper.git .
            git checkout ${RELEASE_TAG}
      - run:
          name: Debug credentials
          command: |
              echo "API key length: ${#RUBYGEMS_API_KEY}"
              echo "Credentials file exists: $(ls -la $HOME/.gem/credentials || echo 'NOT FOUND')"
              # Test API key works
              curl -f -H "Authorization: $RUBYGEMS_API_KEY" https://rubygems.org/api/v1/gems.json > /dev/null && echo "API key valid" || echo "API key invalid"
      - ruby/install-deps
      - run:
          name: Set up credentials
          command: |
              mkdir -p $HOME/.gem
              touch $HOME/.gem/credentials
              chmod 0600 $HOME/.gem/credentials
              printf -- "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > $HOME/.gem/credentials
      - run:
          name: Set version
          command: sed -i "s/[[:digit:]].[[:digit:]].[[:digit:]]/${RELEASE_TAG}/g" $(find . -name "version.rb")
      - run:
          name: Build gem
          command: bundle exec gem build *.gemspec
      - run:
          name: Push gem
          command: bundle exec gem push *.gem

workflows:

  matic-jwt-wrapper.build-pull-request:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:

      - rspec-test:
          context: global
          matrix:
            parameters:
              ruby-version: [ '3.1', '3.2' ]

  matic-jwt-wrapper.release:
    jobs:

      - release:
          tag: << pipeline.git.tag >>
          context: gem-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d\.\d\.\d/ # It should be [digin dot digit dot digit] format
